[package]
edition = "2018"
name = "sentinel"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.59"
clap = {version = "4.0.26", features = ["derive", "cargo"]}
config = "0.13.2"
deref-derive = "0.1.0"
error-stack = "0.2.4"
futures = "0.3.25"
mockall = "0.11.3"
serde = {version = "1.0.147", features = ["derive"]}
serde_json = "1.0.89"
tendermint = "0.27.0"
tendermint-rpc = {version = "0.27.0", features = ["websocket-client"]}
thiserror = "1.0.37"
tokio = "1.22.0"
tokio-stream = {version = "0.1.11", features = ["sync"]}
toml = "0.5.9"
tracing = {version = "0.1.37", features = ["valuable", "log"]}
tracing-core = {version = "0.1.30", features = ["valuable"]}
tracing-subscriber = {version = "0.3.16", features = ["json", "valuable"]}
url = "2.3.1"
valuable = {version = "0.1.0", features = ["derive"]}
