name: Testing

on:
  - pull_request

jobs:
  test:
    strategy:
      matrix:
        os:
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo test
        env:
          RUST_BACKTRACE: '1'
        run: cargo test --release --all-features
